//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FPLibraryClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerInfoTable
    {
        public decimal Customer_ID { get; set; }
        public string Customer_Firrst_Name { get; set; }
        public string Customer_Last_Name { get; set; }
        public string Customer_Password { get; set; }
    }
}
