//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FPLibraryClass
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Papers_and_fishing_luresEntities : DbContext
    {
        public Papers_and_fishing_luresEntities()
            : base("name=Papers_and_fishing_luresEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<P_FL_Fishing> P_FL_Fishing { get; set; }
        public virtual DbSet<P_FL_Paper> P_FL_Paper { get; set; }
    }
}
